const verbTGroup = [
    {
      japanese: "いきます",
      meaningEng: "to go",
      exampleSentence: "がっこうへいきます。",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 2,
      currentWordId: 2
    },
    {
      japanese: "かえります",
      meaningEng: "to return",
      exampleSentence: "いえにかえります。",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 3,
      currentWordId: 3
    },
    {
      japanese: "たべます",
      meaningEng: "to eat",
      exampleSentence: "りんごをたべます。",
      currentGroup: 2,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 4,
      currentWordId: 4
    },
    {
      japanese: "のみます",
      meaningEng: "to drink",
      exampleSentence: "みずをのみます。",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 5,
      currentWordId: 5
    },
    {
      japanese: "みます",
      meaningEng: "to see, watch",
      exampleSentence: "えいがをみます。",
      currentGroup: 2,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 6,
      currentWordId: 6
    },
    {
      japanese: "ききます",
      meaningEng: "to listen",
      exampleSentence: "おんがくをききます。",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 7,
      currentWordId: 7
    },
    {
      japanese: "はなします",
      meaningEng: "to speak",
      exampleSentence: "にほんごをはなします。",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 8,
      currentWordId: 8
    },
    {
      japanese: "します",
      meaningEng: "to do",
      exampleSentence: "しゅくだいをします。",
      currentGroup: 3,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 9,
      currentWordId: 9
    },
    {
      japanese: "べんきょうします",
      meaningEng: "to study",
      exampleSentence: "にほんごをべんきょうします。",
      currentGroup: 3,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 10,
      currentWordId: 10
    },
    {
      japanese: "あります",
      meaningEng: "to exist (inanimate objects)",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 11,
      currentWordId: 11
    },
    {
      japanese: "います",
      meaningEng: "to exist (animate objects)",
      currentGroup: 2,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 12,
      currentWordId: 12
    },
    {
      japanese: "かきます",
      meaningEng: "to write",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 13,
      currentWordId: 13
    },
    {
      japanese: "よみます",
      meaningEng: "to read",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 14,
      currentWordId: 14
    },
    {
      japanese: "ねます",
      meaningEng: "to sleep",
      currentGroup: 2,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 15,
      currentWordId: 15
    },
    {
      japanese: "おきます",
      meaningEng: "to wake up",
      currentGroup: 2,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 16,
      currentWordId: 16
    },
    {
      japanese: "はたらきます",
      meaningEng: "to work",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 17,
      currentWordId: 17
    },
    {
      japanese: "やすみます",
      meaningEng: "to rest",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 18,
      currentWordId: 18
    },
    {
      japanese: "わかります",
      meaningEng: "to understand",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 19,
      currentWordId: 19
    },
    {
      japanese: "おしえます",
      meaningEng: "to teach",
      currentGroup: 2,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 20,
      currentWordId: 20
    },
    {
      japanese: "ならいます",
      meaningEng: "to learn",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 21,
      currentWordId: 21
    },
    {
      japanese: "かいます",
      meaningEng: "to buy",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 22,
      currentWordId: 22
    },
    {
      japanese: "あげます",
      meaningEng: "to give",
      currentGroup: 2,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 23,
      currentWordId: 23
    },
    {
      japanese: "もらいます",
      meaningEng: "to receive",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 24,
      currentWordId: 24
    },
    {
      japanese: "かります",
      meaningEng: "to borrow",
      currentGroup: 2,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 25,
      currentWordId: 25
    },
    {
      japanese: "かします",
      meaningEng: "to lend",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 26,
      currentWordId: 26
    },
    {
      japanese: "きります",
      meaningEng: "to cut",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 27,
      currentWordId: 27
    },
    {
      japanese: "つくります",
      meaningEng: "to make",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 28,
      currentWordId: 28
    },
    {
      japanese: "おくります",
      meaningEng: "to send",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 29,
      currentWordId: 29
    },
    {
      japanese: "いれます",
      meaningEng: "to insert",
      currentGroup: 2,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 30,
      currentWordId: 30
    },
    {
      japanese: "でます",
      meaningEng: "to leave",
      currentGroup: 2,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 31,
      currentWordId: 31
    },
    {
      japanese: "のぼります",
      meaningEng: "to climb",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 32,
      currentWordId: 32
    },
    {
      japanese: "はしります",
      meaningEng: "to run",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 33,
      currentWordId: 33
    },
    {
      japanese: "あそびます",
      meaningEng: "to play",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 34,
      currentWordId: 34
    },
    {
      japanese: "とびます",
      meaningEng: "to jump",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 35,
      currentWordId: 35
    },
    {
      japanese: "まちます",
      meaningEng: "to wait",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 36,
      currentWordId: 36
    },
    {
      japanese: "かたづけます",
      meaningEng: "to tidy up",
      currentGroup: 2,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 37,
      currentWordId: 37
    },
    {
      japanese: "ならべます",
      meaningEng: "to arrange",
      currentGroup: 2,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 38,
      currentWordId: 38
    },
    {
      japanese: "あびます",
      meaningEng: "to bathe",
      currentGroup: 2,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 39,
      currentWordId: 39
    },
    {
      japanese: "つかいます",
      meaningEng: "to use",
      currentGroup: 1,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 40,
      currentWordId: 40
    },
    {
      japanese: "つかれます",
      meaningEng: "to get tired",
      currentGroup: 2,
      numberOfWords: 0,
      checkedNumbers: [""],
      hidde: false,
      difficalId: [],
      difIndex: 0,
      checkHard: false,
      indexCounter: 41,
      currentWordId: 41
    },
  ]

  export default verbTGroup